### ISSUE TITLE
dependency issue - check faul

### ISSUE THREAD

**Issue by thibautjombart** [Hackout2/mapData#2]
From checking out Travis:
- checking package dependencies ... ERROR
  Namespace dependencies not required:
  ‘aggregation’ ‘Calculate’ ‘each’ ‘of’ ‘prevalence’ ‘region’ ‘within’

**Comment by joanna-lewis** [comment]
Thanks Thibaut! I'm working on it and I'll let you know when it's fixed.

**Comment by thibautjombart** [comment]
Awesome!

**Comment by thibautjombart** [comment]
I no longer see this problem in the check, but there are others.
