### ISSUE TITLE
Build currently failing

### ISSUE THREAD

**Issue by joanna-lewis** [Hackout2/mapData#4]
The travis build is currently failing because of a missing dependency (package 'sp') for one of the examples. Could that be because the dependency isn't properly specified?

Thibaut (or anyone else!), please could you advise what the problem might be?

**Comment by thibautjombart** [comment]
@joanna-lewis  you can tag people using @... ;) 
If the package is used in the code, best to use:

``` r
#' ...
#' @importFrom pkg myFunction
#' ...
myFuction <- function(...){
```

If the package is used in the example only, then use something along the lines of 

``` r
if(require(pkg)){
## expl code
}
```

More on this at:
https://cran.r-project.org/doc/manuals/R-exts.html#Package-Dependencies
especially _1.1.3.1 Suggested packages_

**Comment by joanna-lewis** [comment]
Thanks @thibautjombart !

We're already importing the relevant package in the DESCRIPTION file, and roxygen has correctly added import(sp) to the NAMESPACE. I tried 

> #' @examples
> #' if(require(sp)){
> #' < example code >
> #' }

in density_data.R
..but travis still runs the example. (As it should, because the package was imported.)
Any ideas? Sorry to be bothering you with this..

**Comment by thibautjombart** [comment]
Let me give it a try.

**Comment by thibautjombart** [comment]
There was another example. Fixed now. But there are still other issues to solve which currently prevent installation.

**Comment by joanna-lewis** [comment]
Ok, sorry, I didn't see that.

**Comment by thibautjombart** [comment]
I solved a bunch of issues, but some remain. I will post several issues to report problems.

**Comment by joanna-lewis** [comment]
Thanks @thibautjombart . Closing this now, as problems/improvements/documentation questions listed separately as issues.
