### ISSUE TITLE
Embed vignette in README

### ISSUE THREAD

**Issue by thibautjombart** [Hackout2/mapData#9]
I used a trick using a README.Rmd which compiles the vignette and includes it into the output; quite neat as it displays the vignette on the landing page:

Examples can be found there:
https://github.com/thibautjombart/apex
https://github.com/thibautjombart/treescape

**Comment by joanna-lewis** [comment]
I've updated the README to extend the description and include installation instructions. A more extensive, tutorial-type introduction to the package is in a separate vignette.
